views:
  - type: table
    name: Table
    filters:
      and:
        - file.ext == "md"
    order:
      - type
      - title
      - tag
      - status
      - created_at
    sort: []
    columnSize:
      note.title: 198
      note.tag: 90
      note.status: 120
  - type: cards
    name: By Status
    groupBy:
      property: status
      direction: ASC
