CREATE TABLE status (
   id INTEGER PRIMARY KEY,
   name TEXT NOT NULL UNIQUE
);

CREATE TABLE tag (
   id INTEGER PRIMARY KEY,
   name TEXT NOT NULL UNIQUE
);

CREATE TABLE task (
   id INTEGER PRIMARY KEY,
   title TEXT NOT NULL,
   body TEXT,
   status_id INTEGER NOT NULL,
   tag_id INTEGER,
   created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (status_id) REFERENCES status(id)
   FOREIGN KEY (tag_id) REFERENCES tag(id)
);

CREATE TABLE note (
   id INTEGER PRIMARY KEY,
   title TEXT NOT NULL,
   body TEXT,
   created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

